// <auto-generated />
namespace lab3_LaTrungHoa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Createnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202203210405103_Createnew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
